// This file was auto-generated by SRProxy's gen_srproxy.
// DO NOT EDIT IT DIRECTLY.

#pragma once

namespace caf
{
  template<class T> class Proxy;
}

namespace caf
{
  class SRHeader;
  using SRHeaderProxy = caf::Proxy<caf::SRHeader>;
}

namespace caf
{
  class SRVector3D;
  using SRVector3DProxy = caf::Proxy<caf::SRVector3D>;
}

namespace caf
{
  class SRARing;
  using SRARingProxy = caf::Proxy<caf::SRARing>;
}

namespace caf
{
  class SRARingBranch;
  using SRARingBranchProxy = caf::Proxy<caf::SRARingBranch>;
}

namespace caf
{
  class StandardRecord;
  using StandardRecordProxy = caf::Proxy<caf::StandardRecord>;
}

namespace caf{using SRProxy = caf::Proxy<caf::StandardRecord>;}
